Higher level incident call
AlgebraicJulia/DiagrammaticEquations.jl pull request #60
Opened 2024-07-29 21:26 UTC by GeorgeR227

This PR adds a higher level `collected_incident` function that is meant to serve as a replacement to the many reduce-vcats we tend to use when trying to call incident on multiple things at once. Since results from this function are always combined into a single vector of unique results, as opposed to `incident` which may return a vector of vector of results, care must be taken when calling this function into different tables or when calling with multiple inputs.

This function is meant to be generic to work well with the idea that DiagrammaticEquations should have abstracted algorithms but I've also added specific helper functions for Decapodes that may be useful.

2024-07-29 21:54 UTC, lukem12345 commented
Some calls may be better off as `@generated` functions. We should talk about what it would take for this to be in ACSets main at Wednesday's Catlab Developer's meeting.

2024-07-29 22:10 UTC, GeorgeR227 commented
I'd rather not be writing `@generated` calls since we've seen that they don't have their intended effects in ACSets anyway and that'd severely complicate the code.

Having this in ACSets main sounds fine but it leads me to wonder what exactly is supposed to be the difference between ACSets and DiagrammaticEquations.

2024-07-29 22:35 UTC, lukem12345 commented
To ACSets.jl belong data structures and algorithms over generic (not only compute-graph like) schemas. Partitioning the code as of the most recent commit, `src/query.jl` and `test/query.jl` are ACSets.jl-like.

The "query" related code is quite similar to the chained-subparts code, which Sean contributed to ACSets.jl, in that case using CompTime. A recent draft PR demonstrates how using `@generated` to replace that feature allows the Julia compiler to e.g. eliminate intermediate allocations from certain loops.

Sean's PR provides syntactic sugar for nested calls to `incident`. This current PR for adjacent. The code written for the current PR can only be improved by consulting with those sister ones.

2024-08-23 18:34 UTC, jpfairbanks requested changes
@GeorgeR227, could we replace some of this with calls to `querry` from Catlab? 

https://github.com/AlgebraicJulia/Catlab.jl/blob/d336c7bb6b2f7b7e0e105553918c4caccdd99d6f/src/wiring_diagrams/Algebras.jl#L158

It lets you use the relation macro as a declarative DSL for queries. 

Since most queries are a chain of subpart and incident calls, you just write those as simple relations.

If you want to find all the variables that are computed by a direct circularity.
```julia
q = @relation begin
  Op1(src=v, tgt=u)
  Op1(src=u, tgy=v)
end
d = SummationDecapode(...)
query(d, q)
```

This would match patterns like `u = f(v); v = g(u)`. But then you can also do complex patterns like:

```julia
@relation begin
  Op1(src=v, tgt=u)
  Op2(proj1=v, proj2=u, res=x)
end
```

This is a pattern of a triangular dependency where what looks like an op2 on v,u is actually a unary operation on v, because u is derived from v. 

```julia
u = f(v)
x = g(v,u)
```

2024-08-23 18:34 UTC, jpfairbanks commented on test/deca_query.jl
> +    sort(test) == sort(expected)
so you want to handle multiplicity? Could replace with `setequal(a,b) = Set(a) == Set(b)`

2024-08-23 18:34 UTC, jpfairbanks commented on src/deca/deca_query.jl
> +  return collected_incident(d, var, [:tgt, :res, :res, [:summation, :sum]], [:src, :proj1, :proj2, :summand])
I have no idea what this is supposed to do, is this supposed to be a conjucnction of disjunctions type query?

2025-03-14 15:45 UTC, lukem12345 commented
This PR was good for testing out ideas that are now captured by https://github.com/AlgebraicJulia/ACSets.jl/pull/163

2025-03-14 15:45 UTC, closed without merging