Interop with SymbolicUtils
AlgebraicJulia/DiagrammaticEquations.jl pull request #64
Opened 2024-08-14 23:47 UTC by olynch

This is a more-or-less feature-complete conversion between DecaExpr and an equivalent data structure built on SymbolicUtils, but it requires some testing/naming bikeshedding.

2024-08-15 01:08 UTC, lukem12345 commented
@GeorgeR227 Looks like this should get rebased onto https://github.com/AlgebraicJulia/DiagrammaticEquations.jl/pull/54 ; there is apparently some redundancy in dicts for typing/ untyping symbols.

2024-08-15 13:05 UTC, GeorgeR227 commented on src/ThDEC.jl
> +end
I think we need a deeper consideration of the dimension that our physics in occurring in here. I've noticed that the current code is mostly hard-coded for 2D and in the case of the Hodge star, the resulting operator would be wrong if we were working in 1D.

I can say that the way our current inference/overloading rules work is by grouping them into contexts based on the dimension, so we have separate rules to apply in the 1D case and in the 2D case. The way the dimension is figured out is by the user explicitly passing us that information, since some physics can work without modification in multiple dimensions, like the Heat equation.

2024-08-15 13:10 UTC, GeorgeR227 commented
> @GeorgeR227 Looks like this should get rebased onto #54 ; there is apparently some redundancy in dicts for typing/ untyping symbols.

I'm not sure because in this case `OPERATOR_LOOKUP` is taking typed names down to generic names. In that PR we take those typed names down to a single representative which is still typed. It's true that they're similar but their purposes feel different.

2024-08-15 13:49 UTC, lukem12345 commented
Yes the rebase is for purposes of grouping together code that accomplishes similar tasks.

2024-08-16 14:58 UTC, quffaro commented on src/ThDEC.jl
> +end
I think one way to work around this is to store the Space as a parameter in the Form sort. Space may be a wrapper for the dimension of Space, but can be embiggened with other attributes down the line, or maybe even a pointer to the mesh on which its defined, with the provision we have to update our signature checking.

I think this makes philosophical sense. n-forms are the same in any (n+k)-dimensional space, but since they are also determined by duality, their dual varies according to the dimensionality. So this means every n-form is determined by a different dual per dimension. Tagging this dimension `Form(dim, isdual, space)` allows us to track this.

@lukem12345 what do you think about this philosophically and practically?

2024-08-16 16:02 UTC, lukem12345 commented on src/ThDEC.jl
> +end
Philosophically, here are some probing questions: How do you want to distinguish between the Heat equation in 1D, 2D, and 3D? What do morphisms between diagrams (of possibly differing dimension) look like?

Practically: the entire PR seems to be hard-coded for the 2D Discrete Exterior Calculus over a double de Rham complex. I believe more consideration needs to be taken as to how we reconcile having 3 similar algebraic theories in the same package. Is there any advantage to besides code reduction? What is the scale of that code reduction? And is the generalization worth the mental overhead? Are we going to be auto-generating rules by doing index arithmetic on these parameters or not? Do we want it to be clear when we are programming in a 1D environment vs a 3D environment? How does this impact representations with respect to the multi-dimensional multiphysics project? Do we want to represent the various DECs over a single de Rham complex?

2024-08-16 21:08 UTC, olynch commented on src/ThDEC.jl
> +end
This all makes sense. This was supposed to be a first stab at what the API would look like. I think the next step is to add the space to the types, and part of the information about the space will be its dimension.

2024-08-16 21:17 UTC, olynch commented on src/ThDEC.jl
> +end
When we convert a DecaExpr to a DecaSymbolic, you should have to also provide a mapping from space symbol to dimension.

2024-08-16 21:44 UTC, olynch commented on src/ThDEC.jl
> +end
What would you all think of something like:

```julia
struct Space
    name::Symbol
    dim::Int
end

@data Sort begin
    Scalar()
    Form(dim::Int, isdual::Bool, space::Space)
    VField(isdual::Bool, space::Space)
end
```

2024-08-16 21:49 UTC, quffaro commented on src/ThDEC.jl
> +end
@jpfairbanks and I discussed this exact suggestion earlier today. I'd like to implement it, but I think @lukem12345 's practical questions still remain open. @lukem12345 @GeorgeR227 for clarification, should these questions + considerations should be resolved in this PR?

2024-08-16 21:50 UTC, lukem12345 commented on src/ThDEC.jl
> +end
Nothing is immediately keeping this PR open as long as tests pass.

2024-08-21 16:21 UTC, jpfairbanks requested changes

2024-08-21 16:21 UTC, jpfairbanks commented on src/decasymbolic.jl
> +end
this loop should be a function that users can eval to register new symbolic functions. We almost always need at least 1 arbitrary functions that users should be able to register with a syntax like

```julia
@register f(x::PrimalForm{1})::PrimalForm{1}
```

It would also be cool if they could give the implementation there too. 

```julia
@register f(x::PrimalForm{1})::PrimalForm{1} = map(x) do val
  val  ^ 2
end
```

2024-08-21 16:21 UTC, jpfairbanks commented on src/decasymbolic.jl
> +        end
why don't we have to export these like the binops?

2024-08-21 16:34 UTC, jpfairbanks commented
Instead of creating julia functions for the operators of the DEC, could we just create SymbolicUtils function types? 

https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/df8e84d31e60f4dc70f0df2ad88ede91f6f3fd27/src/types.jl#L913

That is what you get when you do:

```julia
julia> @syms f(x)::Complex
(f(::Number)::Complex,)
```

2024-08-22 02:02 UTC, lukem12345 commented on src/decasymbolic.jl
> +            # see test/language.jl
Also fits into best practice of "being liberal in what we accept" https://en.wikipedia.org/wiki/Robustness_principle

2024-08-22 13:59 UTC, jpfairbanks commented on src/ThDEC.jl
> +end
Realized this needs to be default name and dimension

2024-08-23 19:37 UTC, quffaro commented on src/decasymbolic.jl
> +end
Tests currently pass with exception to `klausmeier`. To get it working, @jpfairbanks suggested a `@register` macro to add function terms. However I'm not sure if I'm understanding completely, so I'm seeking clarification. 

Currently (in this PR), for a given operator we define two methods:
1. a  Julia function over `ThDEC` for checking its type. They are aggregated in a OPERATOR_LOOKUP const. This step is analogous to SymbolicUtil's `promote_symtype`
2. a Julia function over `DecaSymbolic`, our type for the SymbolicUtils implementation of ThDEC, which calls (1) for validation

we use the OPERATOR_LOOKUP to also check if a model has admissible terms (e.g.,  Δ), so we want the ability to append the OPERATOR_LOOKUP by `@register`ing new functions.

```{julia}
@register foo(x::Scalar)::Scalar = x + 1
# codegens
foo(s::Scalar) = Scalar
foo(x::BasicSymbolic{T<:DECType}) = begin
    s = foo(Sort(T)) # TYPE CHECKING
    Sym{FnType{Tuple{Number(s)}, Real}(foo)
end
```

Another example comes with a hazard: `PrimalForm{T}` is a parameterized type, but `PrimalForm::Sort` is a function. If we want to continue typechecking with `ThDEC` types, do our current way of checking signatures, we need to make sure codegen for typechecking supports the engineering task to do this.

```{julia}
@register foo(x::PrimalFormT{1})::PrimalFormT{1}
# codegens
foo(x::Form) = @match x begin
    PrimalForm(1) => PrimalForm(1)
    _ => error
end
```

## The steps:

Suppose we wanted to add `foo` to the OPERATOR_LOOKUP dictionary. Notice `PrimalFormT{1}` is the DecaSymbolic type, which accepts parameters.
```{julia}
@register foo(x::PrimalFormT{1})::PrimalFormT{1} = map(x) do val
  val  ^ 2
end
```
We need to define its (1) type-checking (`src/ThDEC`), (2) its DecaSymbolic implementaton (`src/decasymbolic`), and possibly (3) its implementation.

We define the implementation of a function
```{julia}
func(x::PrimalFormT{1})::PrimalFormT{1} = map(x) do val; val ^ 2 end
```
:question: Where does this live? Does this act on BasicSymbolic terms?

Next, we define it symbolically:
```{julia}
symfunc = Sym{FnType{Args, Real}}(ThDEC.func)
```

Then, we add it to OPERATOR_LOOKUP (possible `haskey` validations omitted)
```
ThDEC.OPERATOR_LOOKUP[op] = func
```
:question: Currently OPERATOR_LOOKUP is typed as `Dict{Symbol, Function}`. Is the intent to change `Dict{Symbol, SymbolicFunction}` and do typechecking by replacing the # TYPE CHECKING (above) line with `promote_symtype`?

2024-08-23 20:15 UTC, lukem12345 commented
An implication of Decapode type-inference that seems baked-into this PR is that it is assumed that the choice of primal/ dual is completely inferable based on the types of the parents. However certain operations such as the musical isomorphisms or wedge products can either return a primal or dual form depending on the discrete operator chosen. Note also that for any Decapode, there are multiple means of specifying whether forms are primal or dual. Performing type inference via breadth-first or depth-first traversal at parse-time biases the system towards only representing certain discretizations. In certain cases, choosing a particular discretization for a certain variable or operation may constrain successor operations to certain discretizations, for which CombinatorialSpaces may not yet offer a method. And so a satisfiable model may not be returned, although one may exist.

2024-08-23 21:17 UTC, jpfairbanks commented
We can always do dispatch on return type to let you write sharp(Dual, x)

2024-08-23 22:04 UTC, lukem12345 commented
Yes but that is still local

2024-08-23 22:32 UTC, jpfairbanks commented
I'm moving a comment from @quffaro from inline reply to top level comment so that it stays here after we change the code and mark that thread resolved:

Tests currently pass with exception to `klausmeier`. To get it working, @jpfairbanks suggested a `@register` macro to add function terms. However I'm not sure if I'm understanding completely, so I'm seeking clarification. 

Currently (in this PR), for a given operator we define two methods:
1. a  Julia function over `ThDEC` for checking its type. They are aggregated in a OPERATOR_LOOKUP const. This step is analogous to SymbolicUtil's `promote_symtype`
2. a Julia function over `DecaSymbolic`, our type for the SymbolicUtils implementation of ThDEC, which calls (1) for validation

we use the OPERATOR_LOOKUP to also check if a model has admissible terms (e.g.,  Δ), so we want the ability to append the OPERATOR_LOOKUP by `@register`ing new functions.

```{julia}
@register foo(x::Scalar)::Scalar = x + 1
# codegens
foo(s::Scalar) = Scalar
foo(x::BasicSymbolic{T<:DECType}) = begin
    s = foo(Sort(T)) # TYPE CHECKING
    Sym{FnType{Tuple{Number(s)}, Real}(foo)
end
```

Another example comes with a hazard: `PrimalForm{T}` is a parameterized type, but `PrimalForm::Sort` is a function. If we want to continue typechecking with `ThDEC` types, do our current way of checking signatures, we need to make sure codegen for typechecking supports the engineering task to do this.

```{julia}
@register foo(x::PrimalFormT{1})::PrimalFormT{1}
# codegens
foo(x::Form) = @match x begin
    PrimalForm(1) => PrimalForm(1)
    _ => error
end
```

## The steps:

Suppose we wanted to add `foo` to the OPERATOR_LOOKUP dictionary. Notice `PrimalFormT{1}` is the DecaSymbolic type, which accepts parameters.
```{julia}
@register foo(x::PrimalFormT{1})::PrimalFormT{1} = map(x) do val
  val  ^ 2
end
```
We need to define its (1) type-checking (`src/ThDEC`), (2) its DecaSymbolic implementaton (`src/decasymbolic`), and possibly (3) its implementation.

We define the implementation of a function
```{julia}
func(x::PrimalFormT{1})::PrimalFormT{1} = map(x) do val; val ^ 2 end
```
:question: Where does this live? Does this act on BasicSymbolic terms?

Next, we define it symbolically:
```{julia}
symfunc = Sym{FnType{Args, Real}}(ThDEC.func)
```

Then, we add it to OPERATOR_LOOKUP (possible `haskey` validations omitted)
```
ThDEC.OPERATOR_LOOKUP[op] = func
```
:question: Currently OPERATOR_LOOKUP is typed as `Dict{Symbol, Function}`. Is the intent to change `Dict{Symbol, SymbolicFunction}` and do typechecking by replacing the # TYPE CHECKING (above) line with `promote_symtype`?

2024-08-23 22:43 UTC, jpfairbanks commented
> We define the implementation of a function
> 
> ```
> func(x::PrimalFormT{1})::PrimalFormT{1} = map(x) do val; val ^ 2 end
> ```
> 
> ❓ Where does this live? Does this act on BasicSymbolic terms?

I am rethinking my idea to define the implementation here. The implementations will often need to refer to parts of the mesh, including vertex coordinates or volumes of a simplex. So we should reserve this syntax for defining a new function symbol and a definition in terms of more primitive functions that could get turned into a rewrite. So that you could register a function like 

```julia
f, r = @register f(v::PrimalFormT{1},x::PrimalFormT{0})::PrimalFormT{1} = d(Δ(x)) + (v  ∧ x)
```
and have that expand out to

```julia
f, = @syms f(v::PrimalFormT{1},x::PrimalFormT{0})::PrimalFormT{1}
r = @rule f(~v::PrimalFormT{1},~x::PrimalFormT{0})::PrimalFormT{1} => d(Δ(~x)) + (~v  ∧ ~x)
```

> 
> Next, we define it symbolically:
> 
> ```
> symfunc = Sym{FnType{Args, Real}}(ThDEC.func)
> ```
> 
> Then, we add it to OPERATOR_LOOKUP (possible `haskey` validations omitted)
> 
> ```
> ThDEC.OPERATOR_LOOKUP[op] = func
> ```
> 
> ❓ Currently OPERATOR_LOOKUP is typed as `Dict{Symbol, Function}`. Is the intent to change `Dict{Symbol, SymbolicFunction}` and do typechecking by replacing the # TYPE CHECKING (above) line with `promote_symtype`?

I think that we can create a function for each DEC operator, then create a symbolic function with that function as the head. 

```julia
function Δ end
Δ, = @syms Δ(x::PrimalFormT{0})::PrimalFormT{0}
```

If the function symbol we are creating needs to do dispatch, then it should overload `promote_symtype` to hook that logic into SymbolicUtils the way that it is expected.

2024-08-26 14:22 UTC, lukem12345 commented
https://github.com/AlgebraicJulia/DiagrammaticEquations.jl/issues/35

I think using a defintion operator := like that mentioned in this old issue would be nice.

2024-08-27 20:49 UTC, jpfairbanks requested changes
Looking closer. I put some inline comments on there.

2024-08-27 20:49 UTC, jpfairbanks commented on src/ThDEC.jl
> +                Base.nameof(::typeof($alias), s) = nameof($rep, s)
Do we want the nameof to be the symbol for the alias or the rep? This might break roundtriping because when you print something that used an alias, it will be shown as the rep.

2024-08-27 20:49 UTC, jpfairbanks commented on src/ThDEC.jl
> +@alias d, (d₀, d₁)
maybe using an oriented syntax like 

`@alias (d₀, d₁) => d` will help people remember which is the alias name and which is the alias result.

2024-08-27 20:49 UTC, jpfairbanks commented on src/ThDEC.jl
> +function ⋆(s::Sort)
oh I didn't know about \bigstar. We should use that for hodge star going forward.

2024-08-27 20:49 UTC, jpfairbanks commented on src/decasymbolic.jl
> +            , :♯, :♭, :-]
I don't like commas at the start of the next line. I get that it is valid Julia, but it looks weird.

2024-08-27 20:49 UTC, jpfairbanks commented on src/decasymbolic.jl
> +# BasicSymbolic{FnType{Tuple{PrimalFormT{0}}}, PrimalFormT{0}}
can delete comment

2024-08-27 20:49 UTC, jpfairbanks commented on src/decasymbolic.jl
> +    ! = (f -> getfield(Main, f))
is main always the right module to evaluate this in? I think that we can pass the module in as an argument and have it default to Main. You might want to have two models in the same program that live in different modules.

```
function SymbolicUtils.BasicSymbolic(context::Dict{Symbol,Sort}, t::decapodes.Term, module::Module=Main)
```

should work for a signature.

2024-08-27 20:49 UTC, jpfairbanks commented on src/decasymbolic.jl
> +export @register
Can we use this in all the current unops and binops definitions? It would be good to dogfood the macro to make sure it handles all the cases that we need.

2024-08-27 20:56 UTC, quffaro commented on src/decasymbolic.jl
> +            , :♯, :♭, :-]
Yeah I can one line this. This style is something I picked up from SQL

2024-08-27 20:57 UTC, quffaro commented on src/ThDEC.jl
> +                Base.nameof(::typeof($alias), s) = nameof($rep, s)
Good call, I'll update

2024-08-28 01:46 UTC, jpfairbanks commented on src/decasymbolic.jl
> +    ! = (f -> getfield(Main, f))
You can have a struct with a field that contains a module as a value. So if you just add the module of resolution to the struct as a field and have a macro that uses @__module__ and captures it for future use that is fine. We also only need to resolve which module when we are converting between DecaExpr/ACset and DecaSymbolic. Once we are in DecaSymbolic world, the only module of resolution should the current one. And we shouldn't need to call getfield on a module because we aren't converting symbols to functions, we just have references to the functions we need in the current scope.

2024-09-18 12:31 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
>  function promote_symtype(f::ComposedFunction, args)
We should upstream this method https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/650

2024-10-04 19:07 UTC, GeorgeR227 commented on test/decasymbolic.jl
> +end
@lukem12345 I noticed while going through the `Base.nameof` functionality that support for names of operators with dual inputs is not well supported. Could you advise on how we should be naming these operators to differentiate them from our common primal-primal operators?

2024-10-04 19:08 UTC, GeorgeR227 commented on test/decasymbolic.jl
> +end
I think most notable here is the wedge and the Laplacian.

2024-10-04 19:59 UTC, jpfairbanks commented on test/decasymbolic.jl
> +end
I think that either dual_ or \~ would be appropriate.

2024-10-11 17:15 UTC, merged