Expression level rewriting
AlgebraicJulia/DiagrammaticEquations.jl pull request #69
Opened 2024-08-23 20:37 UTC by GeorgeR227

This PR is meant to create a back-and-forth between ACSets, which excel at information propagation (typing, overloading, etc.) and Symbolics, which excel at expression rewriting (open_operators, optimizations, etc.). 

This should remove the need for our graph rewriting functions and make the workflow to add new rewrites into the system much more faster/cleaner.

2024-08-24 01:11 UTC, jpfairbanks requested changes
The topo sort stuff is looking good. The symbolics integration should target the existing symbolics integration branch.

2024-08-24 01:11 UTC, jpfairbanks commented on src/graph_traversal.jl
> +function number_of_ops(d::SummationDecapode)
nops?

2024-08-24 01:11 UTC, jpfairbanks commented on src/graph_traversal.jl
> +    _ => error("$(tsr.name) is not a valid table for names")
"$(tsr.name) is a table without names"

2024-08-24 01:11 UTC, jpfairbanks commented on test/graph_traversal.jl
> +end
We can also check that when you iterate over the edges in the decapode, we never go from a later vertex to an earlier vertex.

2024-08-24 02:25 UTC, lukem12345 commented
When roundtripping to the SummationDecapode is complete, it would be good to test that the results in `test/openoperators.jl` give the same results up to renaming etc

2024-08-24 16:10 UTC, jpfairbanks commented on src/graph_traversal.jl
> +end
Ok, the unitype design that you did, coupled with an `Enum` that captures the available symbols would be good. https://docs.julialang.org/en/v1/base/base/#Base.Enums.@enum and https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#support-pattern-matching-for-julia-enums could work together to make it easy to write the generic code.

2024-08-30 18:36 UTC, GeorgeR227 commented
I've rebased this branch to work off of PR #64 since the code here will be used for the rewriting using only `Sort`.

2024-09-27 04:01 UTC, lukem12345 commented on src/sym_rewrite.jl
Why is this a source file? @GeorgeR227 @quffaro

2024-09-28 14:52 UTC, GeorgeR227 commented
@lukem12345 We wanted to remove this check since it lead to a lot of special code to handle the final ACSet generation. I've removed it in commit https://github.com/AlgebraicJulia/DiagrammaticEquations.jl/pull/69/commits/5b84cc8a93097832e2a0fa492bba913f17904bba and added the appropriate tests to ensure it's proper functionality.

2024-09-28 14:52 UTC, GeorgeR227 commented on src/sym_rewrite.jl
This is just a scripting file to test out the pipeline, I've tagged it for removal before merging.

2024-09-28 15:02 UTC, lukem12345 commented on src/acset2symbolic.jl
> +  tangents = map(incident(d, DerivOp, :op1)) do op1
This variable is assigned but never used.

2024-09-28 15:10 UTC, GeorgeR227 commented on src/acset2symbolic.jl
> +  tangents = map(incident(d, DerivOp, :op1)) do op1
Removed it now

2024-09-28 16:49 UTC, lukem12345 commented on test/decasymbolic.jl
@quffaro Merge commit 367414d causes “malformed export statement” warnings in the “Operator definition” test set.

2024-09-28 19:01 UTC, GeorgeR227 commented on src/acset2symbolic.jl
> +end
This no longer needs to be passed `d`.

2024-09-28 19:02 UTC, lukem12345 commented on src/acset2symbolic.jl
> +end
Go for it

2024-09-28 19:08 UTC, GeorgeR227 commented on src/acset2symbolic.jl
> +end
Thanks, done

2024-10-03 15:15 UTC, merged