Cm/symbolictypes
AlgebraicJulia/DiagrammaticEquations.jl pull request #71
Opened 2024-08-30 14:21 UTC by quffaro

2024-08-30 14:53 UTC, jpfairbanks requested changes
Mostly bikeshedding things. With an inline comment about adding a method for `promote_symtype` to the registration macro

2024-08-30 14:53 UTC, jpfairbanks commented on src/SymbolicUtilsInterop.jl
> +function SymbolicContext(d::decapodes.DecaExpr, __module__=@__MODULE__)
When you call this with 1 arguement, does this `@__MODULE__` resolves to SymbolicUtilsInterop or to Main?

2024-08-30 14:53 UTC, jpfairbanks commented on src/SymbolicUtilsInterop.jl
> +        j.var => j.var
should the right hand side of this pair be the sort?

2024-08-30 14:53 UTC, jpfairbanks commented on src/deca/ThDEC.jl
> +spacedim(fp::FormParams) = getproperty(fp, :spacedim)
unnecessary use of getproperty. These should just use fp.spacedim etc.

2024-08-30 14:53 UTC, jpfairbanks commented on src/SymbolicUtilsInterop.jl
> +using ..DiagrammaticEquations: AbstractDecapode, Quantity
Where did Quantity come from?

2024-08-30 14:53 UTC, jpfairbanks commented on src/deca/ThDEC.jl
> +abstract type ThDEC <: Quantity end
I'd rather the module be `ThDEC` and the type be `DECType` or `DECQuantity`

2024-08-30 14:53 UTC, jpfairbanks commented on src/deca/ThDEC.jl
> +end
because ACT already means applied category theory. Could we use a one letter name for these like PForm(T)? P for pattern?

2024-08-30 14:53 UTC, jpfairbanks commented on src/deca/ThDEC.jl
> +unops = [:♯, :♭]
unused unops

2024-08-30 14:53 UTC, jpfairbanks commented on src/deca/ThDEC.jl
> +end
register should return the function Δ and a rule that replaces Δ with ⋆(d(⋆(d(x)))) for 0-forms and ⋆(d(⋆(d(x)))) + d(⋆(d(⋆(x)))) for 1 forms. Then we should use it like

```julia
Δ, r_expand_Δ = @register Δ(S)::ThDEC begin
    @match S begin
        ActForm(x) => ⋆(d(⋆(d(x))))
        _ => throw(SortError("Cannot take the Laplacian of $S"))
    end
end
```

2024-08-30 14:53 UTC, jpfairbanks commented on src/deca/ThDEC.jl
> +            (d1 == d2) && (s1 == s2) && (n1 == n2) || throw(SortError("Can only take a wedge product of two forms of the same duality on the same space"))
these errors can be subtypes of `SortError`. So that the error message can be put into the show method for that subtype of `SortError`

2024-08-30 14:53 UTC, jpfairbanks commented on src/deca/ThDEC.jl
> +end
by making more subtypes of Sort error, you won't need a message field. The message can get baked into the subtype's show method.

2024-08-30 14:53 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
> +end
Is this trying to define a show method for Sorts?

2024-08-30 14:53 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
> +     Expr(:block, body...))
spurious code

2024-08-30 14:53 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
> +macro register(head, body)
We should rename this to `@operator`

2024-08-30 14:53 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
> +end
I think we need this function to also emit a `promote_symtype(::typeof{$f}, args...) = f(symtype.(args))` to make rules work.

2024-08-30 16:07 UTC, quffaro commented on src/symbolictheoryutils.jl
> +     Expr(:block, body...))
This will be removed in the next commit. Pushed whatever I had immediately.

2024-08-30 17:52 UTC, quffaro commented on src/symbolictheoryutils.jl
> +end
This is spurious code that was helping me see (hence the name) the AST

2024-08-30 17:58 UTC, quffaro commented on src/deca/ThDEC.jl
> +unops = [:♯, :♭]
Left those to remind myself that they're unimplemented. I'll remove them in next comment

2024-08-30 18:02 UTC, quffaro commented on src/SymbolicUtilsInterop.jl
> +using ..DiagrammaticEquations: AbstractDecapode, Quantity
This is coming from `symbolictheoryutils`, which is not a module. Should I promote `symbolictheoryutils` to a module so it's clear where it's being imported from? Or should I even use `Quantity` at all? I like it as a clothesline to hang BasicSymbolic-integrated theories on, since they are treated as abstract/symbolic quantities which behave like numbers.

2024-08-30 18:07 UTC, jpfairbanks requested changes
Just the docstring and the esc usage comment blocking this

2024-08-30 18:07 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
> +""" ThDEC in DiagrammaticEquations must be subtyped by Number to integrate with SymbolicUtils. An intermediary type, Quantity, makes it clearer that terms in the theory are "symbolic quantities" whic
`DECQuantities` in DiagrammaticEquations must be subtypes of Number to integrate with SymbolicUtils. An intermediary type, Quantity, makes it clearer that terms in the theory are "symbolic quantities" which behave like numbers. In the context of SymbolicUtils, a Number is any type that you can do arithmetic operations on.

2024-08-30 18:07 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
> +@operator foo(S1, S2, ...)::Theory begin
ahh, I see that this return type is like a categories as contexts approach. We are using the abstract type that all of our symbolic quantities inhabit as the "category as context" to anchor the algebraic theory on. I like this as a hybrid between the Catlab/Gatlab approach to explicit theories as the starting point and the SymbolicUtils "a number is a thing you can do math on" approach that minimizes the role of the algebraic theory.

2024-08-30 18:07 UTC, jpfairbanks commented on src/symbolictheoryutils.jl
> +            end
i'm still worried about the overly liberal usage of `esc` here. Not confident that we don't need it here, but we should try to reduce the calls to esc when they aren't needed.

2024-08-30 18:07 UTC, jpfairbanks commented on test/decasymbolic.jl
> +using SymbolicUtils: symtype, promote_symtype
do we need to import to extend?

2024-09-09 14:25 UTC, jpfairbanks requested changes

2024-09-09 14:25 UTC, jpfairbanks commented on test/decasymbolic.jl
>  end
add a test for alias

2024-09-11 13:21 UTC, merged